describe("Tractors in 2023", () => {
        it("passes", () => {
        cy.visit("https://www.tractorjunction.com/");
        cy.wait(3000);
       // cy.clearAllCookies();
        // cy.wait(12000);
        //cy.get('.video-close > .filter-img').click();
        cy.get('#popularnew > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
        cy.wait(2000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
        cy.wait(2000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785  );
        cy.wait(3000);
        cy.get('#statesid').select(34);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
        cy.wait(2000);
        cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
        cy.get('#tractor_submit_form > .tractor_submit').click();
        cy.wait(2000);
        cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
        cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
        cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
        cy.xpath("//a[@title='Receive similar offers']").click();
        //  cy.get('#recom-form > .modal-footer > .btn').click();
     });
     it("Tractors by Budget", () => {
        cy.visit("https://www.tractorjunction.com/");
        cy.wait(3000);
        //cy.clearAllCookies();
        // cy.get('.video-close > .filter-img').click();
        cy.get('#budget3-tab').click();
        cy.wait(2000);
        cy.get('#budget3 > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                 );  cy.wait(3000);
        cy.get('#statesid').select(34);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .tractor_submit').click();
        cy.wait(2000);
        cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
        cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
        cy.wait(2000);
        cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
        cy.xpath("//a[@title='Receive similar offers']").click();
        // cy.get('#recom-form > .modal-footer > .btn').click();
     });
     it("New Tractors listing", () => {
        cy.visit("https://www.tractorjunction.com/tractors/");
       // cy.wait(3000);
       // cy.clearAllCookies();
        cy.wait(12000);
        //cy.get('.video-close > .filter-img').click();
      //  cy.get('.cross').click();
        cy.get(':nth-child(4) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                 );  cy.wait(3000);
        cy.get('#statesid').select(34);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .tractor_submit').click();
        cy.wait(2000);
        cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
        cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
        cy.wait(2000);
        cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
        cy.xpath("//a[@title='Receive similar offers']").click();
        // cy.get('#recom-form > .modal-footer > .btn').click();
     });
     it("Electric Tractors listing", () => {
        cy.visit("https://www.tractorjunction.com/electric-tractors/");
       // cy.wait(3000);
       // cy.clearAllCookies();
        cy.wait(12000);
        // cy.get('.video-close > .filter-img').click();
       // cy.get('.cross').click();
        cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  );   cy.wait(3000);
        cy.get('#statesid').select(34);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .tractor_submit').click();
        cy.wait(2000);
        cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
        // cy.get('.cross').click();
        cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
        cy.wait(2000);
        cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
        cy.xpath("//a[@title='Receive similar offers']").click();
        // cy.get('#recom-form > .modal-footer > .btn').click();
     });
     it("Any brand listing", () => {
        cy.visit("https://www.tractorjunction.com/kubota-tractor/");
        //cy.wait(3000);
       // cy.clearAllCookies();
        cy.wait(12000);
        // cy.get('.video-close > .filter-img').click();
       // cy.get('.cross').click();
        cy.get(':nth-child(3) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  );   cy.wait(3000);
        cy.get('#statesid').select(34);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
        cy.wait(3000);
        cy.get('#tractor_submit_form > .tractor_submit').click();
        cy.wait(2000);
        cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
        //cy.get('.cross').click();
        cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
        cy.wait(2000);
        cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
        cy.xpath("//a[@title='Receive similar offers']").click();
        // cy.get('#recom-form > .modal-footer > .btn').click();
     });
   it("Top Tractor Brands--all-brands", () => {
      cy.visit("https://www.tractorjunction.com/all-brands/");
      cy.wait(3000);
      //  cy.clearAllCookies();
      // cy.wait(12000);
      //cy.get('.cross').click();
      //cy.get('.video-close > .filter-img').click();
      cy.get('#massey-fergusonnew-tab').click();
      cy.wait(2000);
      cy.get('#massey-fergusonnew > .section-css-slider > :nth-child(1) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      //cy.get('#farmtracnew > .viewall > .d-inline-block').click();
      //cy.wait(5000);
      // cy.get('.cross').click();
      //cy.get(':nth-child(5) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785            );
      cyit(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      // cy.get('.cross').click();
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("Tractors by Budget--all-brands", () => {
      cy.visit("https://www.tractorjunction.com/all-brands/");
      //cy.wait(3000);
    //  cy.clearAllCookies();
      cy.wait(12000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('#budget2-tab').click();
      cy.get('#budget2 > .section-css-slider > :nth-child(4) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.wait(2000);
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();

   });
   it("New Product detail page--GORP", () => {
      cy.visit("https://www.tractorjunction.com/indo-farm-tractor/3048-di/");
    //  cy.wait(3000);
     // cy.clearAllCookies();
      cy.wait(12000);
      // cy.get('.video-close > .filter-img').click();
     // cy.get('.cross').click();
      cy.get('.d-none > .row > :nth-child(1) > .tractor_initiate').click();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      //cy.get('.cross').click();
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("New Product detail page--Check Price", () => {
      cy.visit("https://www.tractorjunction.com/valdo-tractor/945-sdi/");
      //cy.wait(3000);
     // cy.clearAllCookies();
      cy.wait(12000);
      //  cy.get('.video-close > .filter-img').click();
      //cy.get('.cross').click();
      cy.get('.emi-price > .requestModal').click();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.wait(3000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      // cy.get('.cross').click();
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();

   });
   it("New Product detail page--Similar section", () => {
      cy.visit("https://www.tractorjunction.com/hav-tractor/50-s2-cng-hybrid/");
    //  cy.wait(3000);
     // cy.clearAllCookies();
      cy.wait(12000);
      // cy.get('.video-close > .filter-img').click();
     // cy.get('.cross').click();
      cy.get('.slick-current > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(2000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785            );
      cyit(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("Used Product detail page--Similar section_ GORP", () => {
      
      cy.visit("https://www.tractorjunction.com/force-tractor/sanman-6000/");
    //  cy.clearAllCookies();
      cy.wait(12000);
      // cy.get('.video-close > .filter-img').click();
    //  cy.get('.cross').click();
      cy.get('[data-slick-index="2"] > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(5000);
      // cy.get('.video-close > .filter-img').click();
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      // cy.get('.cross').click();
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      //cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("compare", () => {
      cy.visit('https://www.tractorjunction.com/compare-tractors/powertrac+euro-42-plus-vs-autonxt+x35h2/');
     // cy.clearAllCookies();
      cy.wait(12000);
      //cy.get('.cross').click();
      // cy.get('.video-close > .filter-img').click();
      cy.scrollTo(0, 1000)
      cy.wait(2000);
      cy.get('#fixedTop1 > .v_btnRoad > .requestModal').click();
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
      //cy.get('#recom-form > .modal-footer > .btn').click();
      //cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      // cy.wait(2000);
      // cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      //cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("on-road-price", () => {
      cy.visit("https://www.tractorjunction.com/on-road-price/");
     // cy.clearAllCookies();
      cy.wait(12000);
      //cy.get('.cross').click();
      // cy.get('.video-close > .filter-img').click();
      cy.get('#brand_id').select(2);
      cy.get('#modelreview').select(1);
      cy.wait(3000);
      cy.get('#validationDefault01').clear();
      cy.get('#validationDefault01').type("testqa");
      cy.wait(3000);
      cy.get('#validationDefault03').type(9158593785                  ); cy.get('.col-sm-12 > .form-group > .form-control').select(35);
      cy.wait(3000);
      cy.get('.row > :nth-child(6) > .form-group > .form-control').select(64);
      cy.wait(3000);
      cy.get(':nth-child(7) > .form-group > .form-control').select(3);
      cy.wait(3000);
      cy.get('.col-md-8 > #tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
      // cy.wait(2000);
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("Tractor News landing page", () => {
      cy.visit("https://www.tractorjunction.com/tractor-news/murugappa-group-launches-3-new-electric-tractors-this-fiscal/");
      //cy.clearAllCookies();
      cy.wait(3000);
      //cy.get('.cross').click();
      // cy.get('.video-close > .filter-img').click();
      cy.get(':nth-child(2) > .tractorCardSingle-box > .tractorCardSingle-cont > .tractorCardSingle-btn > .btn-global').click();
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();

   });
   it("EMI Calculator result page_GORP", () => {
      cy.visit('https://www.tractorjunction.com/tractor-loan-emi-calculator/kartar/5036-4wd/');
     // cy.clearAllCookies();
      cy.wait(12000);
      //  cy.get('.video-close > .filter-img').click();
      cy.get('.borderBtn').click();
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.wait(3000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
   });
   it("Dealers result page_Popular section", () => {
      cy.visit('https://www.tractorjunction.com/find-tractor-dealers/escort/');
     // cy.clearAllCookies();
      cy.wait(12000);
      // cy.get('.video-close > .filter-img').click();
      cy.get('.tractor_initiate').click();
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
   });
   it("service centre result page_Popular section", () => {
      cy.visit('https://www.tractorjunction.com/tractor-service-centers/vst-shakti/');
     // cy.clearAllCookies();
      cy.wait(2000);
      // cy.get('.video-close > .filter-img').click();
      cy.get(':nth-child(3) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.wait(3000);
      cy.get('#statesid').select(34);
      cy.wait(3000);
      cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.wait(2000);
      cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.get('#tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//a[@title='Receive similar offers']").click();
   });
   it("new tractor-loan", () => {
      cy.visit("https://www.tractorjunction.com/tractor-loan/");
     // cy.clearAllCookies();
      cy.wait(2000);
      //  cy.get('.video-close > .filter-img').click();
      cy.get('#step1 > :nth-child(3) > .input-group > .form-control').clear();
      cy.wait(2000);
      cy.get('#step1 > :nth-child(3) > .input-group > .form-control').type("testqa");
      cy.wait(2000);
      cy.get(':nth-child(4) > .input-group > .form-control').type(9158593785                  ); cy.get(':nth-child(5) > .form-group > .loc-edit').click();
      cy.get(':nth-child(5) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("Noida");
      cy.wait(3000);
      cy.get(':nth-child(5) > .form-group > .loc-edit').click();
      cy.get('#locations > li > a').click();
      cy.get('#SubmitStepForm1').click();
      // cy.wait(3000);
      // cy.get(':nth-child(5) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').click();
      cy.wait(3000);
      cy.get('#aadharInput').type("000000000000");
      cy.get('#panCardInput').type("ABCD1234");
      cy.get('#SubmitStepForm2').click();
      cy.wait(2000);
      cy.get('.form-container > .thaks-form-wapper > .thaks-form-content > h5').should('exist');
   });
   it("personal-loan", () => {
      cy.visit("https://www.tractorjunction.com/personal-loan/");
     // cy.clearAllCookies();
      cy.wait(2000);
      // cy.get('.video-close > .filter-img').click();
      cy.get('#step1 > :nth-child(3) > .input-group > .form-control').clear();
      cy.get('#step1 > :nth-child(3) > .input-group > .form-control').type("testqa");
      cy.wait(2000);
      cy.get(':nth-child(4) > .input-group > .form-control').type(9158593785                  ); cy.get(':nth-child(5) > .form-group > .loc-edit').click();
      cy.get(':nth-child(5) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("noida");
      cy.get('#locations > li > a').click();
      cy.get('#SubmitStepForm1').click();
      cy.get('#aadharInput').type("00000000000");
      cy.get('#panCardInput').type("ABCD123");
      cy.get('#SubmitStepForm2').click();
      cy.get('.form-container > .thaks-form-wapper > .thaks-form-content > h5').should('exist');
   });
   it("Loan landing page_ Finance", () => {
      cy.visit('https://www.tractorjunction.com/loan/');
    //  cy.clearAllCookies();
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('#loannewit').select(1);
      cy.get(':nth-child(2) > .input-group > .form-control').clear();
      cy.wait(2000);
      cy.get(':nth-child(2) > .input-group > .form-control').type('testqa');
      cy.wait(2000);
      cy.get(':nth-child(3) > .input-group > .form-control').type(9158593785                  ); cy.get(':nth-child(4) > .form-group > .loc-edit').click({ force: true });
      cy.get(':nth-child(4) > .form-group > #locationPlaceholder').type('noida');
      cy.wait(2000);
      cy.get('#locations > li > a').click();
      cy.wait(3000);
      cy.get('#SubmitLoanForm').click({ force: true });
      cy.wait(3000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   });
   it("News landing_Used Tractor Loan", () => {
      cy.visit('https://www.tractorjunction.com/tractor-news/murugappa-group-launches-3-new-electric-tractors-this-fiscal/');
      //cy.clearAllCookies();
      // cy.wait(12000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('.Offerinner > :nth-child(1) > .form-group > .form-control').clear({ force: true });
      cy.wait(2000);
      cy.get('.Offerinner > :nth-child(1) > .form-group > .form-control').type('testqa', { force: true });
      cy.wait(2000);
      cy.get('.Offerinner > :nth-child(2) > .form-group > .form-control').type(9158593785                  , { fe: true });
      cy.wait(3000);
      cy.xpath("(//div[@class='loc-edit'])[1]").click({ force: true });
      cy.wait(2000);
      cy.xpath("(//input[@id='cityName'])[1]").type('noida', { force: true });
      cy.wait(2000);
      cy.xpath("(//a[text()='Noida, Uttar Pradesh, India'])[1]").click({ force: true });
      cy.get('.OfferSelectBtn').click({ force: true });
      cy.wait(2000);
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated fadeInDown']//span[3]").should('exist');

   });
   it("EMI Calculator result page_Loan", () => {
      cy.visit("https://www.tractorjunction.com/tractor-loan-emi-calculator/kartar/5036-4wd/");
      ///cy.clearCookies();
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('.emi-months-wrp > .loanOffer-btn-row > .w-100').click();
      cy.wait(2000);
      cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(1) > .form-control').clear();
      cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(2) > .form-control').type(9158593785                  ); cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > .col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
      cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > .col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
      cy.get('#locations > li > a').click();
      cy.get('#Loan-popup-new > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .new_tractor_loan_btn').click();
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');

   });
   it("Request call back", () => {
      cy.visit("https://www.tractorjunction.com/massey-ferguson-tractor/");
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
      cy.xpath("//img[@class='cross']").click();
      cy.get('.call-with-animation > img').click();
      cy.wait(2000);
      cy.get('#name').clear();
      cy.get('#name').type('testqa');
      cy.wait(2000);
      cy.get('#mobile').type(9158593785                  ); cy.xpath("(//div[@class='loc-edit'])[1]").click();
      cy.get('#RequestCallBackDataBrand > .row > .sell-form-view > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
      cy.get('#RCBlocations > li > a').click();
      cy.get('#model_id').select(2);
      cy.get('#RequestCallBackSingleBrand').click();
      cy.get('#recom-form > .modal-footer > .btn').click();
      cy.get('[data-notify="message"]').should('exist');
   });
   // same error massage
   it("Request call back", () => {
      cy.visit("https://www.tractorjunction.com/indo-farm-tractor/3048-di/");
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
     // cy.get('.cross').click();
      cy.get('.call-with-animation > img').click();
      cy.wait(2000);
      cy.get('#name').clear();
      cy.get('#name').type('testqa');
      cy.wait(2000);
      cy.get('#mobile').type(9158593785                  ); cy.xpath("(//div[@class='loc-edit'])[1]").click();
      cy.get('#RequestCallBackData > .row > .col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
      cy.get('#RCBlocations > li > a').click();
      cy.get('#RequestCallBackSingle').click();
      cy.get('[data-notify="message"]').should('exist');
      //cy.get('.cross').click();
      // cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      // cy.get('#recom-form > .modal-footer > .btn').click();

   });

   it("Request call back - Sticky", () => {
      cy.visit("https://www.tractorjunction.com/shop/service-kit/");
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('.headphone-icon').click();
      cy.wait(2000);
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').clear();
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(2) > .input-group > .form-control').type('9158593785                       ');
      cy.get('.RequestWidgetCallBackform > .fillBtn').click();
      cy.wait(2000);
      cy.get('[data-notify="message"]').should('exist');
   });
   it("Request call back", () => {
      cy.visit("https://www.tractorjunction.com/shop/service-kit/");
      cy.wait(2000);
      // cy.get('.video-close > .filter-img').click();
      cy.get(':nth-child(1) > .part-product-main > .part-product-detail > .req-call-btn > .req-button-list').click();
      cy.wait(2000);
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').clear();
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('.RequestWidgetCallBackform > .row > :nth-child(2) > .input-group > .form-control').type('9158593785                       ');
      cy.get('.RequestWidgetCallBackform > .fillBtn').click();
      cy.wait(2000);
      cy.get('[data-notify="message"]').should('exist');
   });
   it("News Listing page--Request call back", () => {
      cy.visit("https://www.tractorjunction.com/news/");
      cy.wait(2000);
      // cy.get('.video-close > .filter-img').click();
      cy.get('.call-with-animation > img').click();
      cy.wait(2000);
      cy.get('#name').clear();
      cy.get('#name').type('testqa');
      cy.wait(2000);
      cy.get('#mobile').type('9158593785                        ');
      cy.xpath("(//div[@class='loc-edit'])[1]").click();
      cy.get('#RequestCallBackDataNews > .row > .sell-form-view > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
      cy.get('#RCBlocations > li > a').click();
      cy.get('#brand_id').select(2);
      cy.wait(2000);
      cy.get('#model_id_option').select(2);
      cy.get('#RequestCallBackSingleBrand').click();
      cy.wait(2000);
      cy.get('[data-notify="message"]').should('exist');
      // cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      // cy.get('#recom-form > .modal-footer > .btn').click();
   });
   it("News landing page--Request call back", () => {
      cy.visit("https://www.tractorjunction.com/agriculture-news/this-new-variety-of-mustard-will-make-farmers-rich/");
      cy.get('.call-with-animation > img').click();
      cy.wait(2000);
      cy.get('#name').clear();
      cy.get('#name').type('testqa');
      cy.wait(2000);
      cy.get('#mobile').type('9158593785                       ');
      // cy.xpath("(//div[@class='loc-edit'])[2]").click();
      cy.get('#RequestCallBackDataNews > .row > .sell-form-view > .sell-view-inner > .form-group > .loc-edit > span').click();
      cy.get('#RequestCallBackDataNews > .row > .sell-form-view > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
      cy.get('#RCBlocations > li > a').click();
      cy.get('#brand_id').select(2);
      cy.wait(2000);
      cy.get('#model_id_option').select(2);
      cy.get('#RequestCallBackSingleBrand').click();
      cy.wait(2000);
      cy.get('[data-notify="message"]').should('exist');
      //  cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
      //cy.get('#recom-form > .modal-footer > .btn').click();

   });
   it("Krish-e form", () => {
      cy.visit("https://www.tractorjunction.com/hi/krishe/");
      cy.wait(2000);
      //  cy.get('.video-close > .filter-img').click();
      cy.get('#inputname').clear();
      cy.get('#inputname').type("testqa");
      cy.wait(2000);
      cy.get('#inputnumber').type(8439237649);
      cy.get(':nth-child(3) > .form-group > .loc-edit').click();
      cy.get(':nth-child(3) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("noida");
      cy.get('#locations > li > a').click();
      cy.get('#submitEKrishe').click();
      cy.get('[data-notify="message"]').should('exist');
   });
   it("AMP", () => {
      cy.viewport(375, 667);
      cy.visit("https://www.tractorjunction.com/mahindra-tractor/oja-2127-4wd/?amp=1");
      //cy.wait(3000);
      cy.scrollTo(0, 1000);
      cy.wait(3000);
      cy.get('#scrollToTopButton > .tjrow > :nth-child(1) > .tractor_initiate').click();
      // cy.wait(12000);
      //cy.get('.video-close > .filter-img').click();
      cy.get('#validationDefault01').clear();
      cy.get('#validationDefault01').type("testqa");
      cy.wait(3000);
      cy.get('#validationDefault03').type(8439237649);
      cy.get('.col-sm-12 > .form-group > .form-control').select(35);
      cy.wait(3000);
      cy.get('.row > :nth-child(6) > .form-group > .form-control').select(64);
      cy.wait(3000);
      cy.get('.row > :nth-child(7) > .form-group > .form-control').select(2);
      cy.wait(3000);
      cy.get('.col-md-8 > #tractor_submit_form > .tractor_submit').click();
      cy.wait(2000);
      cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
      cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
      cy.xpath("//a[@title='Receive similar offers']").click();
   });
   it('should display correctly in mobile view', () => {
      cy.viewport(375, 667);
      cy.visit('https://www.tractorjunction.com/kubota-tractor/l3408/');
      cy.wait(2000);
      //cy.get('.video-close > .filter-img').click();
     // cy.get('.cross').click();
      cy.get('.viewOffers > .requestModal').click();
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
      cy.wait(2000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
      cy.wait(2000);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(2) > .form-control').type(8439237649);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(3) > #statesid').select(34);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
      cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #tractor_submit_form > .tractor_submit').click();
      cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close').click();
      cy.get('[data-notify="message"]').should('exist');
      cy.get('#recom-form > .modal-footer > .btn').click();

   });
});

















/*
// used tractor detail page pe se contact seller nikal diya hai--new reliease
it("Contact seller", () => {
cy.visit("https://www.tractorjunction.com/used-tractor/sonalika/sonalika-50-rx-sikander-136567/152545/");
cy.wait(12000);
cy.get('.video-close > .filter-img').click();
cy.wait(2000);
cy.get('#name').clear();
cy.get('#name').type('testqa');
cy.wait(2000);
cy.get(':nth-child(7) > #buyermobile').type('9158593785                       ');
cy.wait(2000);
cy.get('#inputState').select(35);
cy.wait(2000);
cy.get('#inputdistric').select(64);
cy.get('#price').type(200);
cy.get(':nth-child(1) > .form-submit-btn').click();
cy.get('.btn-border').click();
cy.get('#contactSellerInfo > .modal-dialog > .modal-content > .customModal-header > .modalHeading').should('exist');
});
it("Used tractor listing page==Loan", () => {
cy.visit('https://www.tractorjunction.com/used-tractor/sonalika/rx-55-dlx-136690/152668/');
cy.wait(12000);
cy.get('.video-close > .filter-img').click();
cy.get('.row > :nth-child(2) > .form-submit-btn').click();
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(1) > .form-control').clear();
cy.wait(2000);
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(1) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > :nth-child(2) > .form-control').type(8439237649);
cy.get(':nth-child(3) > #tractorYear').select(3);
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > .col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .row > .col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
cy.wait(2000);
cy.get('#locations > li > a').click();
cy.get('#Loan-popup-used > .modal-dialog > .modal-content > .customModal-body > #loan-validation > .new_tractor_loan_btn').click();
cy.wait(3000);
cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
});
it("used-tractors-for-sell", () => {
cy.visit("https://www.tractorjunction.com/used-tractors-for-sell/");
cy.wait(2000);
cy.scrollTo(0,1500);
cy.wait(2000);
cy.xpath("//span[@data-form_name='Loan ticker']//img").click();
cy.get(':nth-child(1) > .custom-select').select(1);
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').clear();
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(3) > .form-control').type(8439237649);
cy.get('.col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
cy.wait(2000);
cy.get('.col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
cy.get('#locations > li > a').click();
cy.get('#loan-validation > .new_tractor_loan_btn').click();
cy.get('[data-notify="message"]').should('exist');


it("Used tractor listing page----Loan Sticky", () => {
cy.visit("https://www.tractorjunction.com/tractors/");
cy.scrollTo(0,500);
cy.wait(2000);
cy.xpath("//span[@data-form_name='Loan ticker']//img").click();
cy.get(':nth-child(1) > .custom-select').select(1);
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').clear();
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(3) > .form-control').type(8287914965 );
cy.xpath("(//input[@id='cityName'])[1]").type('noida',{force: true});
cy.wait(2000);
cy.xpath("(//a[text()='Noida, Uttar Pradesh, India'])[1]").click({force: true});
cy.get('.new_tractor_loan_btn').click();
cy.get('[data-notify="message"]').should('exist');
});
it("Used tractor listing page--Loan Sticky", () => {
cy.visit("https://www.tractorjunction.com/eicher-tractor/");
cy.scrollTo(0,500);
cy.wait(2000);
cy.xpath("//span[@data-form_name='Loan ticker']//img").click();
cy.get(':nth-child(1) > .custom-select').select(1);
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').clear();
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(3) > .form-control').type(8080395543);
cy.get('.col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
cy.wait(2000);
cy.get('.col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
cy.get('#locations > li > a').click();
cy.get('#loan-validation > .new_tractor_loan_btn').click();
cy.get('[data-notify="message"]').should('exist');
});
});
//Used tractor listing page--loan (bug hai live me)
describe("Lead Regression", () => {
it("passes", () => {
cy.visit("https://www.tractorjunction.com/agriculture-news/this-new-variety-of-mustard-will-make-farmers-rich/");
cy.scrollTo(0,1000);
cy.wait(2000);
cy.get('.loan-popup-all > img').click();
cy.get(':nth-child(1) > .custom-select').select(2);
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').clear();
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').type('testqa');
cy.get('#loan-validation > .row > :nth-child(3) > .form-control').type(9415254680);
cy.get('#tractorYear').select(2);
cy.get('.col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
cy.get('.col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
cy.get('#locations > li > a').click();
cy.get('#loan-validation > .new_tractor_loan_btn').click();
cy.get('.col-xs-11').should('exist');
});
});
 //compare page--landing page----problem(bug ahe same number second time lead submmited no any msg display)
describe("Lead Regression", () => {
it("passes", () => {
 cy.visit('https://www.tractorjunction.com/compare-tractors/farmtrac+6055-t20-powermaxx-vs-powertrac+euro-45-plus-4wd/');
cy.get('.carCompare-inner1 > .seprate-compare > .carCompare-inner-in > .carCompare-content-detail > .compre-on-road').click();
cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
cy.wait(2000);
cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9311689784);
cy.wait(3000);
cy.get('#statesid').select(2);
cy.wait(3000);
cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(3);
cy.wait(2000);
cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(1);
cy.wait(2000);
cy.get('#tractor_submit_form > .tractor_submit').click();
cy.wait(2000);
cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
cy.wait(2000);
cy.xpath("//a[@title='Receive similar offers']").click();
cy.wait(2000);
cy.xpath("(//div[@class='col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span)[3]").should('exist');
});
});
// bug hai live me
describe("Lead Regression", () => {
it("passes", () => {
cy.visit("https://www.tractorjunction.com/agriculture-news/this-new-variety-of-mustard-will-make-farmers-rich/");
cy.scrollTo(0,1000);
cy.wait(2000);
cy.xpath("//span[@data-form_name='Loan ticker']//img").click();
cy.get(':nth-child(1) > .custom-select').select(1);
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').clear();
cy.get('#loan-validation > .row > :nth-child(2) > .form-control').type('testqa');
cy.wait(2000);
cy.get('#loan-validation > .row > :nth-child(3) > .form-control').type(9311689784);
cy.get('.col-12 > .sell-view-inner > .form-group > .loc-edit > span').click();
cy.wait(2000);
cy.get('.col-12 > .sell-view-inner > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type('noida');
cy.get('#locations > li > a').click();
cy.get('#loan-validation > .new_tractor_loan_btn').click();
cy.get('[data-notify="message"]').should('exist');
});
it("loan-against-tractor", () => {
cy.visit("https://www.tractorjunction.com/loan-against-tractor/");
cy.wait(2000);
// cy.get('.video-close > .filter-img').click();
cy.get('#step1 > :nth-child(3) > .input-group > .form-control').clear();
cy.wait(2000);
cy.get('#step1 > :nth-child(3) > .input-group > .form-control').type("testqa");
cy.wait(2000);
cy.get(':nth-child(4) > .input-group > .form-control').type(9953591178     );
cy.get(':nth-child(5) > .form-group > .loc-edit').click();
cy.get(':nth-child(5) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("noida");
cy.get('#locations > li > a').click();
cy.get('#SubmitStepForm1').click();
cy.get('#year-div > .form-group > #tractorYear').select(2);
cy.get('#aadharInput').type("0000000000");
cy.get('#panCardInput').type("ABCD123");
cy.get('#SubmitStepForm2').click();
cy.get('.form-container > .thaks-form-wapper > .thaks-form-content > h5').should('exist');
});
it("used-tractor-loan", () => {
cy.visit("https://www.tractorjunction.com/used-tractor-loan/");
cy.wait(2000);
// cy.get('.video-close > .filter-img').click();
cy.get('#step1 > :nth-child(3) > .input-group > .form-control').clear();
cy.wait(2000);
cy.get('#step1 > :nth-child(3) > .input-group > .form-control').type("testqa");
cy.wait(2000);
cy.get(':nth-child(4) > .input-group > .form-control').type(9953591178     );
cy.get(':nth-child(5) > .form-group > .loc-edit').click();
cy.get(':nth-child(5) > .form-group > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("noida");
cy.get('#locations > li > a').click();
cy.get('#SubmitStepForm1').click();
cy.get('#year-div > .form-group > #tractorYear').select(2);
cy.get('#aadharInput').type("00000000000");
cy.get('#panCardInput').type("ABCD1234");
cy.get('#SubmitStepForm2').click();
cy.get('.form-container > .thaks-form-wapper > .thaks-form-content > h5').should('exist');
}); 
 
});
*/

