describe("Tractors in 2023", () => {
 it("Tractors in 2023_popularnew-tab", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#popularnew > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178      );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(2000); 
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
 });
 it("Tractors in 2023_latestnew-tab", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#latestnew-tab').click();
    cy.get('#latestnew > .section-css-slider > :nth-child(1) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178      );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(2000); 
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
 });
 it("Tractors in 2023_upcomingnew-tab", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#upcomingnew-tab').click();
    cy.get('#upcomingnew > .section-css-slider > :nth-child(1) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(2000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178      );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(2000); 
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
 });

   // this lead from depends upon location ticket whens this funcatinality live the update code.
 it("Tractors in 2023_premium-tab", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#premium-tab').click();
    cy.get('#premium > .section-css-slider > :nth-child(4) > .global-wrapper-Usedtractor > .revamp-tractor-box > .used-tractor-main > .used-tractor-content > .used-tractor-anchor').click();
    cy.get('#used_tractor_lead_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(2000);
    cy.get('#used_tractor_lead_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(2000);
    cy.get('#used_tractor_lead_form > .row > :nth-child(2) > .form-control').type(9953591178      );
    cy.wait(2000);
    cy.get('#price').type(100);

    cy.get('.new_tractor_seller_btn').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
 });

it("Tractors by Budget_below 3 lakh", () => {
   cy.visit("https://www.tractorjunction.com/");
   cy.wait(12000);
   cy.get('.video-close > .filter-img').click();
   cy.get('#budget1-tab').click();
   cy.wait(2000);
   cy.get('#budget1 > .section-css-slider > :nth-child(1) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
   cy.wait(3000);
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
   cy.wait(3000);
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
   cy.wait(3000);
   cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
   cy.wait(3000);
   cy.get('#statesid').select(34);
   cy.wait(3000);
   cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
   cy.wait(3000);
   cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
   cy.wait(3000);
   cy.get('#tractor_submit_form > .tractor_submit').click();
   cy.wait(2000);
   cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
   cy.wait(2000);
   cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
   cy.xpath("//a[@title='Receive similar offers']").click();
  // cy.get('#recom-form > .modal-footer > .btn').click();
});
it("Tractors by Budget_3 lakh - 5 lakh", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#budget2-tab').click();
    cy.wait(2000);
    cy.get('#budget2 > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("Tractors by Budget_5 lakh - 7 lakh", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#budget3-tab').click();
    cy.wait(2000);
    cy.get('#budget3 > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("Tractors by Budget_7 lakh - 10 lakh", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#budget4-tab').click();
    cy.wait(2000);
    cy.get('#budget4 > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("Tractors by above 10 lakh", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('#budget5-tab').click();
    cy.wait(2000);
    cy.get('#budget5 > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("MiNi_Tractors", () => {
    cy.visit("https://www.tractorjunction.com/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.container-mid > .section-css-slider > :nth-child(2) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("All tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(4) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("popular-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/popular-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("upcoming-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/upcoming-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(5) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("latest-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/latest-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("Electric Tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/electric-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("mini-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/mini-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("4wd-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/4wd-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("ac-cabin-tractors listing_In header", () => {
    cy.visit("https://www.tractorjunction.com/ac-cabin-tractors/");
    cy.wait(12000);
    cy.get('.video-close > .filter-img').click();
    cy.get('.cross').click();
    cy.get(':nth-child(6) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').clear();
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178     );
    cy.wait(3000);
    cy.get('#statesid').select(34);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
    cy.wait(3000);
    cy.get('#tractor_submit_form > .tractor_submit').click();
    cy.wait(2000);
    cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   // cy.get('.cross').click();
    cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
    cy.xpath("//a[@title='Receive similar offers']").click();
   // cy.get('#recom-form > .modal-footer > .btn').click();
 });
 it("Certified Used Tractor(desktop)_contact seller", () => {
   cy.visit("https://www.tractorjunction.com/assured-used-tractors-for-sell/");
 });
 it("compare page_check tractor price button(upper side widge-scroll down )", () => {
 cy.visit('https://www.tractorjunction.com/compare-tractors/powertrac+euro-42-plus-vs-autonxt+x35h2/');
 cy.wait(12000);
 //cy.get('.cross').click();
// cy.get('.video-close > .filter-img').click();
 cy.scrollTo(0,1000)
 cy.wait(2000);
 cy.get('#fixedTop1 > .v_btnRoad > .requestModal').click();
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9953591178  );
 cy.wait(3000);
 cy.get('#statesid').select(34);
 cy.wait(3000);
 cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
 cy.get('#tractor_submit_form > .tractor_submit').click();
 cy.wait(2000);
 cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close').click();
 cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
 //cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
 cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
 cy.wait(2000);
 cy.xpath("//a[@title='Receive similar offers']").click();
});
it("compare page_check tractor price", () => {
   cy.visit('https://www.tractorjunction.com/compare-tractors/digitrac+pp-51i-vs-sonalika+wt-60-sikander/');
   cy.get('.carCompare-inner1 > .seprate-compare > .carCompare-inner-in > .carCompare-content-detail > .compre-on-road').click();
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9082539192);
 cy.wait(3000);
 cy.get('#statesid').select(34);
 cy.wait(3000);
 cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
 cy.get('#tractor_submit_form > .tractor_submit').click();
 cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
 cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
 cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
 cy.get('#recom-form > .modal-footer > .btn').click();
});
it("compare page_popular_check tractor price", () => {
   cy.visit('https://www.tractorjunction.com/compare-tractors/digitrac+pp-51i-vs-sonalika+wt-60-sikander/');
   cy.get('#popularnew > .section-css-slider > :nth-child(3) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9082539192);
 cy.wait(3000);
 cy.get('#statesid').select(34);
 cy.wait(3000);
 cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
 cy.get('#tractor_submit_form > .tractor_submit').click();
 cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
 cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
 cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
 cy.get('#recom-form > .modal-footer > .btn').click();
});
it("compare page_latest_check tractor price", () => {
   cy.visit('https://www.tractorjunction.com/compare-tractors/digitrac+pp-51i-vs-sonalika+wt-60-sikander/');
   cy.wait(2000);
   cy.get('#latestnew-tab').click();
   cy.get('#latestnew > .section-css-slider > :nth-child(4) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9082539192);
 cy.wait(3000);
 cy.get('#statesid').select(34);
 cy.wait(3000);
 cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
 cy.get('#tractor_submit_form > .tractor_submit').click();
 cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
 cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
 cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
 cy.get('#recom-form > .modal-footer > .btn').click();
});
it("compare page_upcoming_check tractor price", () => {
   cy.visit('https://www.tractorjunction.com/compare-tractors/digitrac+pp-51i-vs-sonalika+wt-60-sikander/');
   cy.wait(2000);
   cy.get('#upcomingnew-tab').click();
   cy.get('#upcomingnew > .section-css-slider > :nth-child(3) > .new-tractor-main > .mb-2 > .tractor_initiate').click();
   cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').clear();
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(1) > .form-control').type('testqa');
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(2) > .form-control').type(9082539192);
 cy.wait(3000);
 cy.get('#statesid').select(34);
 cy.wait(3000);
 cy.get('#tractor_submit_form > .row > :nth-child(4) > .custom-select').select(64);
 cy.wait(2000);
 cy.get('#tractor_submit_form > .row > :nth-child(5) > .custom-select').select(3);
 cy.get('#tractor_submit_form > .tractor_submit').click();
 cy.get('#VerifyMobileNumber > .modal-dialog > .modal-content > .close > .filter-img').click();
 cy.get('#enquirypopup > .modal-dialog > .modal-content > .thankModal-header > .request-title > h3').should('exist');
 cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile > .checkbox-icon').click();
 cy.get('#recom-form > .modal-footer > .btn').click();
});
it("on-road-price", () => {
   cy.visit("https://www.tractorjunction.com/on-road-price/");
   cy.wait(12000);
   //cy.get('.cross').click();
  // cy.get('.video-close > .filter-img').click();
   cy.get('#brand_id').select(2);
   cy.get('#modelreview').select(1);
   cy.wait(3000);
   cy.get('#validationDefault01').clear();
   cy.get('#validationDefault01').type("testqa");
   cy.wait(3000);
   cy.get('#validationDefault03').type(7042347930      );
   cy.get('.col-sm-12 > .form-group > .form-control').select(35);
   cy.wait(3000);
   cy.get('.row > :nth-child(6) > .form-group > .form-control').select(64);
   cy.wait(3000);
   cy.get(':nth-child(7) > .form-group > .form-control').select(3);
   cy.wait(3000);
   cy.get('.col-md-8 > #tractor_submit_form > .tractor_submit').click();
   cy.wait(2000);
   cy.xpath("//div[@class='ssss col-xs-11 col-sm-4 alert alert-success success-message-right animated bounceInDown']//span[3]").should('exist');
   cy.get(':nth-child(1) > .checkbox-wrapper > .checkbox-tile').click();
   cy.xpath("//a[@title='Receive similar offers']").click();
  // cy.wait(2000);
  // cy.get('#recom-form > .modal-footer > .btn').click();
});
it("Request call back - Sticky", () => {
   cy.visit("https://www.tractorjunction.com/shop/service-kit/");
   cy.wait(2000);
   //cy.get('.video-close > .filter-img').click();
   cy.get('.headphone-icon').click();
   cy.wait(2000);
   cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').clear();
   cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').type('testqa');
   cy.wait(2000);
   cy.get('.RequestWidgetCallBackform > .row > :nth-child(2) > .input-group > .form-control').type('7042347930      ');
   cy.get('.RequestWidgetCallBackform > .fillBtn').click();
   cy.wait(2000);
   cy.get('[data-notify="message"]').should('exist');
});
  it("Request call back", () => {
  cy.visit("https://www.tractorjunction.com/shop/service-kit/");
  cy.wait(2000);
 // cy.get('.video-close > .filter-img').click();
  cy.get(':nth-child(1) > .part-product-main > .part-product-detail > .req-call-btn > .req-button-list').click();
  cy.wait(2000);
  cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').clear();
  cy.get('.RequestWidgetCallBackform > .row > :nth-child(1) > .input-group > .form-control').type('testqa');
  cy.wait(2000);
  cy.get('.RequestWidgetCallBackform > .row > :nth-child(2) > .input-group > .form-control').type('7042347930      ');
  cy.get('.RequestWidgetCallBackform > .fillBtn').click();
  cy.wait(2000);
  cy.get('[data-notify="message"]').should('exist');
}); 

});