describe("Truck Junction Lead Regression", () => {
  it("Truck in 2024_popular", () => {
    cy.visit("https://trucks.tractorjunction.com/");
   // cy.clearAllCookies();
     cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#truck-popular > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522     );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Truck in 2024_latest", () => {
    cy.visit("https://trucks.tractorjunction.com/");
    cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-truck-latest').click();
    cy.get('#truck-latest > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Truck in 2024_upcoming", () => {
    cy.visit("https://trucks.tractorjunction.com/");
     cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-truck-upcoming').click();
    cy.get('#truck-upcoming > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Latest Models by Category_trucks--Tata 1412 LPT", () => {
    cy.visit("https://trucks.tractorjunction.com/");
    cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#trucks > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    //cy.wait(2000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Latest Models by Category_trailer", () => {
    cy.visit("https://trucks.tractorjunction.com/");
    cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-tractor').click();
    cy.get('#tractor > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    //cy.wait(2000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Latest Models by Category_mini trucks", () => {
    cy.visit("https://trucks.tractorjunction.com/");
    cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-mini-truck').click();
    cy.get('#mini-truck > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    //cy.wait(2000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Find New Truck listing", () => {
    cy.visit("https://trucks.tractorjunction.com/en/new-trucks");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    //cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("new-truck-loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/new-truck-loan?utm_source=push_ads");
     cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
    cy.get(':nth-child(3) > .input-group > .form-control').type(9554407522                  );
    cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get('#loanSubmit').click();
    cy.get('.thaks-form-content > h5').should('have.text', 'Thank you for your interest!');
  });
  it("used-truck-loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/used-truck-loan?utm_source=push_ads");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
    cy.get(':nth-child(3) > .input-group > .form-control').type(9554407522                  );
    cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get('#loanSubmit').click();
    cy.get('.thaks-form-content > h5').should('have.text', 'Thank you for your interest!');
  });
  it("loan-against", () => {
    cy.visit("https://trucks.tractorjunction.com/en/loan-against-truck?utm_source=push_ads");
     cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
    cy.get(':nth-child(3) > .input-group > .form-control').type(9554407522                  );
    cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get('#loanSubmit').click();
    cy.get('.thaks-form-content > h5').should('have.text', 'Thank you for your interest!');
  });
  it("Personal Loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/personal-loan?utm_source=push_ads");
     cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
    cy.get(':nth-child(3) > .input-group > .form-control').type(9554407522                  );
    cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get('#loanSubmit').click();
    cy.get('.thaks-form-content > h5').should('have.text', 'Thank you for your interest!');
  });
  it("comapre_pickups", () => {
    cy.visit("https://trucks.tractorjunction.com/en/compare");
    cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-pickup').click();
    cy.get('#trucks > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("comapre_3 wheelers", () => {
    cy.visit("https://trucks.tractorjunction.com/en/compare");
    cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-three-wheeler').click();
    cy.get('#three-wheeler > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();

  });
  it("compare", () => {
    cy.visit("https://trucks.tractorjunction.com/en/compare/ashok-leyland+1916-hh-4x2-vs-bharat-benz+1015r");
     cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.offset-md-1 > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);

    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
    cy.wait(5000);

    cy.get(':nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > .float-left').clear();
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("EMI Calculator result page_GORP---EMI Calculator page", () => {
    cy.visit("https://trucks.tractorjunction.com/en/emi-calculator/altigreen/neev-low-deck-2140electric");
     cy.wait(3000);
    //    cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522             );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(3000);
    //  cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("EMI Calculator result page_Loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/emi-calculator/altigreen/neev-low-deck-2140electric");
    cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.emi-months-wrp > .loanOffer-btn-row > .w-100').click();
    cy.get('#loannewit').select(1);
    cy.wait(3000);
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
    cy.get(':nth-child(3) > .input-group > .form-control').type(9554407522                  );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get('#loanSubmit').click();
    cy.get('.thaks-form-content > h5').should('have.text', 'Thank you for your interest!');
  });
  it("On road Price page---GORP form", () => {
    cy.visit("https://trucks.tractorjunction.com/en/onroadprice");
     cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(2000);
    cy.get(':nth-child(1) > .form-group > .form-control').clear();
    cy.get(':nth-child(1) > .form-group > .form-control').type('testqa');
    cy.wait(2000);
    cy.get(':nth-child(2) > .form-group > .form-control').type(9554407522                  );
    //cy.get('.form-group > .loc-edit').click();
    cy.get('.form-group > .float-left').type('noida');
    cy.get('.form-group > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get(':nth-child(4) > .form-group > .form-control').select(3);
    cy.get(':nth-child(5) > .form-group > .form-control').select(3);
    cy.wait(3000);
    //cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get(':nth-child(6) > .form-group > .form-control').select(2);
    cy.get('#SubmitOnroadPrice').click();
    cy.get('.thankscustomModal-header > .modalHeading').should('have.text', 'Thank You!!!');
  });
  it("New Product detail page-GORP (Mahindra Jeeto Plus Petrol Mini Truck", () => {
    cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/jeeto-petrol");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.get('.col-12.d-flex > .fillBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Call button (tata-truck/yodha-2-0)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/yodha-2-0");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.get('.green-btn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);

    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Check offer--ashok-leyland-truck/3520", () => {
    cy.visit("https://trucks.tractorjunction.com/en/ashok-leyland-truck/3520");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.get('.check-offers-btn > .d-none').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(3000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .fillBtn').click();
  });
  it("New Product detail page--EMI Check offer--ashok-leyland-truck/3520", () => {
    cy.visit("https://trucks.tractorjunction.com/en/ashok-leyland-truck/3520");
    cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.check-offers-btn > .d-none').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(3000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#loanPopupFormData > .fillBtn').click();
  });
  it("New Product detail page--Book free test drive(eicher-truck)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/eicher-truck/pro-2049");
    cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.variants-compare > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Variants section_GORP(sml-isuzu-truck)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/sml-isuzu-truck/samrat-gs");
     cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .variants-td-btn > .linkclr > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Call now poupup(mahindra-truck/supro-van)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/supro-van");
    cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.calltel > .d-inline-block').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Other Trucks section(tata-truck/ultra-2821t)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/ultra-2821t");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close').click();
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(9) > .truckCardSingle-container > .truckCardSingle-slide > :nth-child(2) > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Download Brochure--isuzu-truck/d-max  -- last", () => {
    cy.visit("https://trucks.tractorjunction.com/en/isuzu-truck/d-max");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.emiOffer-btn > .GetOnRoadPriceForm').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Popular New Trucks", () => {
    cy.visit("https://trucks.tractorjunction.com/en/blue-energy-truck/5528-4x2");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.xpath("(//span[text()='Check Offers'])[4]").click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);

    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New Product detail page--Commercial Vehicles by Fuel Type", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/signa-1918k-322545m3-box");
      cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-a6').click();
    cy.get('#a6 > .truckCardSingle-slide > :nth-child(1) > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("New product detail page-Popular Second Hand Truck section", () => {
    cy.visit("https://trucks.tractorjunction.com/en/volvo-truck/fm-420-4x2-lng");
     cy.wait(3000);
    //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(7) > .truckCardSingle-container > .truckCardSingle-slide > .truckCardSingle-wrap > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .btn-global').click();
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522            );
    cy.wait(2000);
    //cy.get('#contactSellerDetailForm > .row > :nth-child(3) > .form-control').type(200);
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type('noida');
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.wait(2000);
    cy.get('#SubmitOnroadPriceForm').click();
    cy.get('#sellerdetailsubmission > .modal-dialog > .modal-content > .customModal-header > .modalHeading').should('exist');
  });
  it("New product detail page-Variants section_Loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/1512-lpt");
      cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(4) > .variants-td-price > .offer-price > .mx-1').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#loanPopupFormData > .fillBtn').click();
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("New product detail page-Loan Offers widget", () => {
    cy.visit("https://trucks.tractorjunction.com/en/maruti-suzuki-truck/super-carry");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.mb-3 > .location-position > .new-popup-location > .float-left').type('noida');
    cy.get('.mb-3 > .location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get(':nth-child(2) > .form-group > #Name').clear();
    cy.get(':nth-child(2) > .form-group > #Name').type('testqa');
    cy.wait(2000);
    cy.get(':nth-child(3) > .form-group > #phone').type(9554407522                  );
    cy.get(':nth-child(4) > .row > .col-12 > .fillBtn').click();
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("New product detail page-view loan offers- EMI calculater widget", () => {
    cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/alfa-dx");
     cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.loanOffer-btn-row > .w-100').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("noida");
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#loanPopupFormData > .fillBtn').click();
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("New product detail page-connect now-talk to dealer section", () => {
    cy.visit("https://trucks.tractorjunction.com/en/scania-truck/p-320-4x2");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.emiOffer.d-block > .emiOffer-container > .emiOffer-Wrapper > .emiOffer-content > .emiOffer-content-in > .emiOffer-plan-in > .emiOffer-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').clear();
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').type("testqa");
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(2) > #mobile').type(9554407522                  );
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    // cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("New Product detail page-Truck Dealers & Service Centers section", () => {
    cy.visit("https://trucks.tractorjunction.com/en/bharat-benz-truck/4828rt");
     cy.wait(3000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#truck-dealers > .row > :nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .boldfont').click();
    cy.wait(3000);
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').clear();
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').type("testqa");
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(2) > #mobile').type(9554407522                  );
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    // cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(1)').click();
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > #SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("New Product detail page--Call us - calling button (tata-truck/yodha-2-0)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/sml-isuzu-truck/samrat-1312-xt");
     cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.call-us-button').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Price in loacation page- verify GORP lead", () => {
    cy.visit('https://trucks.tractorjunction.com/en/sml-isuzu-truck/samrat-gs-2815cab/price/jaipur');
    cy.wait(2000);
    cy.get('.blue-Btn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Specification page- verify Loan lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/man-truck/cla-31300-evo-8x4/specifications");
    cy.wait(3000);
    cy.get('.check-offers-btn > .d-none').click();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(3000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("noida");
    cy.wait(2000);
    cy.get(':nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();

    cy.get('#loanPopupFormData > .fillBtn').click();
  });
  it("Mileage page- Verify GORP lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/sml-isuzu-truck/supreme-gs-3335cab/mileage");
    cy.wait(2000);
    cy.get('.blue-Btn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Compare page- verify GORP lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/isuzu-truck/s-cab/compare");
    cy.wait(3000);
    cy.get('.truckCompare-content-detail > .hand-cursor').click();
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522             );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Compare page- verify GORP lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/isuzu-truck/s-cab/loan");
    cy.wait(3000);
    cy.get('.location-position > .new-popup-location > .float-left').type('noida');
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > .d-block').click();
    cy.get(':nth-child(2) > .form-group > #Name').type('testqa');
    cy.get(':nth-child(3) > .form-group > #phone').type('9554407522                          ');
    cy.get(':nth-child(4) > .row > .col-12 > .fillBtn').click();
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("Image page- verify calling button lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/bharat-benz-truck/5528tt/images");
    cy.wait(3000);
    cy.get('.call-us-button').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Image page- verify calling button lead", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/1512-lpt/brochure");
    cy.wait(3000);
    cy.get('.download-brochure-wrp > .download-brochure-btn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.wait(2000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Service center page (only with location)- Verify dealer lead", () => {
    cy.visit('https://trucks.tractorjunction.com/en/service-center/tata/tamil-nadu/chennai');
    cy.wait(3000);
    cy.get(':nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .btn-global').click();
    cy.wait(2000);
    cy.get('#name').clear();
    cy.wait(2000);
    cy.get('#name').type('testqa');
    cy.get('#mobile').type(9554407522                  );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#brand_id').select(2);
    cy.get('#model_id').select(1);
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("Spare part page (only with location)- Verify dealer lead", () => {
    cy.visit('https://trucks.tractorjunction.com/en/spare-parts/tata/tamil-nadu/chennai');
    cy.wait(3000);
    cy.get(':nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .btn-global').click();
    cy.wait(2000);
    cy.get('#name').clear();
    cy.get('#name').type('testqa');
    cy.get('#mobile').type(9554407522                  );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#brand_id').select(2);
    cy.get('#model_id').select(1);
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("Videos page- verify GORP lead", () => {
    cy.visit('https://trucks.tractorjunction.com/en/ashok-leyland-truck/2825-rmc-39007m3-cum/videos');
    cy.wait(3000);
    cy.get('.col-12.d-flex > .blue-Btn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Electric vehicle product Detail page_check offers", () => {
    cy.visit('https://trucks.tractorjunction.com/en/triton-ev-truck/semi-truck');
    cy.wait(3000);
    cy.get('.floatingMobile-left > .fillBtn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(3000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("apply loan on hero section", () => {
    cy.visit('https://trucks.tractorjunction.com/en/triton-ev-truck/semi-truck');
    cy.wait(3000);
    cy.get('.floatingMobile-right > .hand-cursor').click();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type('noida');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .fillBtn').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("bus product  Detail page_check offers", () => {
    cy.visit('https://trucks.tractorjunction.com/en/triton-ev-truck/semi-truck');
    cy.wait(3000);
    cy.get('.floatingMobile-left > .fillBtn').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9554407522             );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    //  cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(3000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("apply loan on hero section", () => {
    cy.visit('https://trucks.tractorjunction.com/en/triton-ev-truck/semi-truck');
    cy.wait(3000);
    cy.get('.floatingMobile-right > .hand-cursor').click();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9554407522                  );
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type('noida');
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .fillBtn').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
  it("Find New Truck listing", () => {
    cy.visit("https://trucks.tractorjunction.com/en/new-trucks");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    //cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Any brand listing---Brand Listing Page--ashok-leyland", () => {
    cy.visit("https://trucks.tractorjunction.com/en/ashok-leyland");
    cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
    //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(3)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Top Truck Brands--mahindra", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
    cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-truck-mahindra').click();
    cy.get('#truck-mahindra > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Latest Models by Category--volvo", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-tractor').click();
    cy.get('#tractor > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Trucks By Budget--solar energy rickshow", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
    cy.wait(3000);
    //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#budget1 > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Popular bus listing page", () => {
    cy.visit("https://trucks.tractorjunction.com/en/buses/popular");
    cy.wait(3000);
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Top Bus brands", () => {
    cy.visit("https://trucks.tractorjunction.com/en/buses/brands");
    cy.wait(3000);
    cy.get('#bus-ashok-leyland > .newTruckBlock > :nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(3000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Bus by seating capacity", () => {
    cy.visit("https://trucks.tractorjunction.com/en/buses/brands");
    cy.wait(3000);
    cy.get('#seat2-tab').click();
    cy.get('#seat2 > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(3000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Bus By Budget", () => {
    cy.visit("https://trucks.tractorjunction.com/en/buses/brands");
    cy.wait(3000);
    cy.get('#budget3-tab').click();
    cy.get('#budget3 > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(2000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(3000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });
  it("Electric Vehicle listing_GORP", () => {
    cy.visit("https://trucks.tractorjunction.com/en/electric");
    cy.wait(3000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9554407522                  );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    //cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
    //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(3)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
  });

  it("Body_makers", () => {
    cy.visit("https://trucks.tractorjunction.com/en/body-makers");
    cy.wait(3000);
    cy.get(':nth-child(2) > .dealerBlock-inner > .dealer-inner-content > .dealerBlock-contact > .linkclr').click();
    cy.get('#name').clear();
    cy.wait(2000);
    cy.get('#name').type("testqa");
    cy.get('#mobile').type(9554407522                  );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#SubmitDealerLead').click();
    cy.xpath("//div[@class='toast-body']").should('exist');
  });
});