    describe("Truck Junction Lead Regression", () => {
    it("passes", () => {
    cy.visit("https://trucks.tractorjunction.com/");
   // cy.wait(12000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#truck-popular > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279   );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Latest Models by Category--Tata 1412 LPT", () => {
    cy.visit("https://trucks.tractorjunction.com/");
  //  cy.wait(12000);
 //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#trucks > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279   );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.wait(3000);
    //cy.wait(2000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Find New Truck listing", () => {
    cy.visit("https://trucks.tractorjunction.com/en/new-trucks");
    //cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279   );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
   
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Electric Vehicle listing_GORP", () => {
    cy.visit("https://trucks.tractorjunction.com/en/electric");
  //  cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279   );
    cy.xpath("(//input[@name='locationPlaceholder'])[2]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    //cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(3)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Bus listing page--e bus", () => {
    cy.visit("https://trucks.tractorjunction.com/en/buses");
  //  cy.wait(12000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Any brand listing---Brand Listing Page--ashok-leyland", () => {
    cy.visit("https://trucks.tractorjunction.com/en/ashok-leyland");
   // cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(2) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[2]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(3)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Top Truck Brands--mahindra", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
  //  cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-truck-mahindra').click();
    cy.get('#truck-mahindra > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    //cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Latest Models by Category--volvo", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-tractor').click();
    cy.get('#tractor > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("Trucks By Budget--solar energy rickshow", () => {
    cy.visit("https://trucks.tractorjunction.com/en/brands");
   // cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#budget1 > .newTruckBlock > :nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#Name').clear();
    cy.get('#Name').type("testqa");
    cy.get('#phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('.check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page-GORP (Mahindra Jeeto Plus Petrol Mini Truck", () => {
    cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/jeeto-petrol");
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.col-12.d-flex > .fillBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
   // cy.get(':nth-child(5) > .new-popup-location > .float-left').click();
   cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
   cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
  //  cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Call button (tata-truck/yodha-2-0)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/yodha-2-0");
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.green-btn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
   cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
//cy.get('.modal-content > .close > .filter-img').click();
  //  cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Check offer--ashok-leyland-truck/3520", () => {
    cy.visit("https://trucks.tractorjunction.com/en/ashok-leyland-truck/3520");
    //cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.check-offers-btn > .d-none').click();
    cy.wait(2000);
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.wait(3000);
    cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    //cy.xpath("(//div[@class='loc-edit'])[5]").click();
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("Noida");
    cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#loanPopupFormData > .fillBtn').click();
});
    it("New Product detail page--Book free test drive(eicher-truck)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/eicher-truck/pro-2049");
   // cy.wait(12000);
 //   cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.variants-compare > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
   // cy.xpath("(//div[@class='loc-edit'])[4]").click();
   cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
   cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Variants section_GORP(sml-isuzu-truck)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/sml-isuzu-truck/samrat-gs");
  //  cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .variants-td-btn > .linkclr > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    //cy.xpath("(//div[@class='loc-edit'])[4]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Call now poupup(mahindra-truck/supro-van)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/supro-van");
   // cy.wait(12000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.calltel > .d-inline-block').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    
    it("New Product detail page--Other Trucks section(tata-truck/ultra-2821t)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/ultra-2821t");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close').click();
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(9) > .truckCardSingle-container > .truckCardSingle-slide > :nth-child(1) > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    //cy.xpath("(//div[@class='loc-edit'])[4]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Download Brochure--isuzu-truck/d-max  -- last", () => {
    cy.visit("https://trucks.tractorjunction.com/en/isuzu-truck/d-max");
    //cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.emiOffer-btn > .GetOnRoadPriceForm').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Popular New Trucks", () => {
    cy.visit("https://trucks.tractorjunction.com/en/blue-energy-truck/5528-4x2");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.xpath("(//span[text()='Check Offers'])[4]").click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Commercial Vehicles by Fuel Type", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/signa-1918k-322545m3-box");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close').click();
    cy.get('#nav-a6').click();
    cy.get('#a6 > .truckCardSingle-slide > :nth-child(1) > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
    //cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Similar New Truck section", () => {
    cy.visit("https://trucks.tractorjunction.com/en/olectra-truck/6x4-electric");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.get(':nth-child(1) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
  //  cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("New Product detail page--Landing_Popular Models By Application", () => {
    cy.visit("https://trucks.tractorjunction.com/en/select-your-truck");
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-Application1').click();
    cy.get('#Application1 > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
   // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("select-your-truck --Result_Listing", () => {
    cy.visit("https://trucks.tractorjunction.com/en/select-your-truck/mining"); 
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(6) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("select-your-truck --landing page_Popular Models by Category", () => {
    cy.visit("https://trucks.tractorjunction.com/en/compare"); 
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#nav-pickup').click();
    cy.get('#pickup > .newTruckBlock > :nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   // cy.get('.modal-content > .close > .filter-img').click();
   // cy.wait(3000);
  //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("compare", () => {
    cy.visit("https://trucks.tractorjunction.com/en/compare/ashok-leyland+1916-hh-4x2-vs-bharat-benz+1015r"); 
  //  cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('.offset-md-1 > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
    cy.wait(3000);
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
    cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
  //  cy.get('.modal-content > .close > .filter-img').click();
  //  cy.wait(3000);
   // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.wait(5000);
    
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
});
    it("On road Price page---GORP form", () => {
     cy.visit("https://trucks.tractorjunction.com/en/onroadprice");
   //  cy.wait(12000);
   //  cy.get('.modal-content > .close > .filter-img').click();
     cy.wait(2000);
     cy.get(':nth-child(1) > .form-group > .form-control').clear();
     cy.get(':nth-child(1) > .form-group > .form-control').type('testqa');
     cy.wait(2000);
     cy.get(':nth-child(2) > .form-group > .form-control').type(9650252279    );
     cy.get('.form-group > .float-left').type('noida');
     cy.get('.form-group > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
     cy.get(':nth-child(4) > .form-group > .form-control').select(3);
     cy.get(':nth-child(5) > .form-group > .form-control').select(3);
     cy.wait(3000);
    //cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get(':nth-child(6) > .form-group > .form-control').select(2);
     cy.get('#SubmitOnroadPrice').click();
     cy.get('.thankscustomModal-header > .modalHeading').should('have.text','Thank You!!!'); 
    });
     it("Find Dealers_Result_Similar Wheelers--On road Price page", () => {
     cy.visit("https://trucks.tractorjunction.com/en/dealers/mahindra/uttar-pradesh/noida");
   //  cy.wait(12000);
   //  cy.get('.modal-content > .close > .filter-img').click();
     cy.get(':nth-child(3) > .newTruckBlock-inner > .newTruckBlock-content > .borderBtn').click();
     cy.wait(3000);
     cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
     cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
     cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
     cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
     cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
     cy.wait(3000);
    // cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
   //  cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
     cy.get('#SubmitOnroadPriceForm').click();
     cy.wait(5000);
     cy.get('.thankscustomModal-header > .modalHeading').should('exist');
     cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
    }); 
     it("Spare Parts_talk to dealer---On road Price page", () => {
     cy.visit("https://trucks.tractorjunction.com/en/spare-parts/ashok-leyland/uttar-pradesh/noida");
 //    cy.wait(12000);
   //  cy.get('.modal-content > .close > .filter-img').click();
     cy.get(':nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .btn-global').click();
     cy.wait(3000);
     cy.get('#name').clear();
     cy.get('#name').type("testqa");
     cy.get('#mobile').type(9650252279    );
     cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
     cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
     cy.get('#brand_id').select(1);
     cy.get('#model_id').select(2);
     cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
     //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
     cy.get('#SubmitDealerLead').click();
     cy.wait(3000);
     cy.xpath("//div[@class='toast-body']").should('exist');
    });
     it("Spare Parts_Similar Trucks---On road Price page", () => {
     cy.visit("https://trucks.tractorjunction.com/en/spare-parts/ashok-leyland/uttar-pradesh/noida");
 //    cy.wait(12000);
 //    cy.get('.modal-content > .close > .filter-img').click();
     cy.get(':nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .btn-global').click();
     cy.wait(3000);
     cy.get('#name').clear();
     cy.get('#name').type("testqa");
     cy.get('#mobile').type(9650252279    );
     cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
     cy.wait(2000);
     cy.get('#brand_id').select(2);
     cy.wait(2000);
     cy.get('#model_id').select(2);
     cy.wait(3000);
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
    // cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
     cy.get('#SubmitDealerLead').click();
     cy.xpath("//div[@class='toast-header bg-success text-white']").should('exist');
    });
     it("EMI Calculator result page_GORP---EMI Calculator page", () => {
     cy.visit("https://trucks.tractorjunction.com/en/emi-calculator/altigreen/neev-low-deck-2140electric");
    // cy.wait(12000);
     //cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
     cy.get('.borderBtn').click();
     cy.wait(3000);
     cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
     cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
     cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9773375071    );
     cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
   //  cy.wait(2000);
    // cy.get('.modal-content > .close > .filter-img').click();
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
     //cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
     cy.get('#SubmitOnroadPriceForm').click(); 
     cy.get('.thankscustomModal-header > .modalHeading').should('exist');
     cy.get('#thanksPopup > .modal-dialog > .modal-content > .close > img').click();
    });
     it("Talk to dealer 2", () => {
     cy.visit("https://trucks.tractorjunction.com/en/force");
  //   cy.wait(12000);
  //   cy.get('.modal-content > .close > .filter-img').click();
     cy.get('#truck-dealers > .row > :nth-child(1) > .dealerBlock-inner > .dealer-inner-content > .dealerBlock-contact > .linkclr').click();
     cy.wait(3000);
     cy.get('#name').clear();
     cy.get('#name').type("testqa");
     cy.get('#mobile').type(9650252279    );
     cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
     cy.get('#model_id').select(2);
     cy.wait(3000);
     
    // cy.get('#turno-popup > .modal-dialog > .modal-content > .close > .filter-img').click();
     //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
     cy.get('#SubmitDealerLead').click();
     cy.wait(3000);
     cy.xpath("//div[@class='toast-body']").should('exist');
    });
     
     it("new-truck-loan", () => {
     cy.visit("https://trucks.tractorjunction.com/en/new-truck-loan?utm_source=push_ads");
    // cy.wait(12000);
    // cy.get('.modal-content > .close > .filter-img').click();
     cy.wait(3000);
     cy.get(':nth-child(2) > .input-group > .form-control').clear();
     cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
     cy.get(':nth-child(3) > .input-group > .form-control').type(9650252279);
     cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
     cy.wait(2000);
     cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
     cy.wait(2000);
     cy.get('#loanSubmit').click();
     cy.get('.thaks-form-content > h5').should('have.text','Thank you for your interest!');
    });

     it("used-truck-loan", () => {
     cy.visit("https://trucks.tractorjunction.com/en/used-truck-loan?utm_source=push_ads");
    // cy.wait(12000);
    // cy.get('.modal-content > .close > .filter-img').click();
     cy.wait(3000);
     cy.get(':nth-child(2) > .input-group > .form-control').clear();
     cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
     cy.get(':nth-child(3) > .input-group > .form-control').type(9650252279    );
     cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
     cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
    cy.wait(2000);
     cy.get('#loanSubmit').click();
     cy.get('.thaks-form-content > h5').should('have.text','Thank you for your interest!');
    });

     it("loan-against", () => {
     cy.visit("https://trucks.tractorjunction.com/en/loan-against-truck?utm_source=push_ads");
   //  cy.wait(12000);
    // cy.get('.modal-content > .close > .filter-img').click();
     cy.wait(3000);
     cy.get(':nth-child(2) > .input-group > .form-control').clear();
     cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
     cy.get(':nth-child(3) > .input-group > .form-control').type(9650252279    );
     cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
     cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
    cy.wait(2000);
     cy.get('#loanSubmit').click();
     cy.get('.thaks-form-content > h5').should('have.text','Thank you for your interest!');
    });

     it("Personal Loan", () => {
     cy.visit("https://trucks.tractorjunction.com/en/personal-loan?utm_source=push_ads");
  //   cy.wait(12000);
  //   cy.get('.modal-content > .close > .filter-img').click();
     cy.wait(3000);
     cy.get(':nth-child(2) > .input-group > .form-control').clear();
     cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
     cy.get(':nth-child(3) > .input-group > .form-control').type(9650252279    );
     cy.xpath("(//input[@name='locationPlaceholder'])[1]").click();
     cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
    cy.wait(2000);
     cy.get('#loanSubmit').click();
     cy.get('.thaks-form-content > h5').should('have.text','Thank you for your interest!');
    });

     it("EMI Calculator result page_Loan", () => {
     cy.visit("https://trucks.tractorjunction.com/en/emi-calculator/altigreen/neev-low-deck-2140electric");
    // cy.wait(12000);
   //  cy.get('.modal-content > .close > .filter-img').click();
     cy.get('.emi-months-wrp > .loanOffer-btn-row > .w-100').click();
     cy.get('#loannewit').select(1);
     cy.wait(3000);
     cy.get(':nth-child(2) > .input-group > .form-control').clear();
     cy.get(':nth-child(2) > .input-group > .form-control').type("testqa");
     cy.get(':nth-child(3) > .input-group > .form-control').type(9650252279    );
     cy.get('.location-position > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('.location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
    cy.wait(2000);
     cy.get('#loanSubmit').click();
     cy.get('.thaks-form-content > h5').should('have.text','Thank you for your interest!');
    });

     it("Loan", () => {
     cy.visit("https://trucks.tractorjunction.com/en/mahindra-truck/alfa-dx");
   //  cy.wait(12000);
    // cy.get('.modal-content > .close > .filter-img').click();
     cy.get('.loanOffer-btn-row > .w-100').click();
     cy.wait(2000);
     cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
     cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
     cy.wait(2000);
     cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9650252279    );
     cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("noida");
     cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
     cy.get('#loanPopupFormData > .fillBtn').click();
     cy.xpath("//div[@class='toast-body']").should('exist');
    });

     it("Variants section_Loan", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/1512-lpt");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close').click();
    cy.get(':nth-child(4) > .variants-td-price > .offer-price > .mx-1').click();
    cy.wait(2000);
     cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').clear();
     cy.get('#loanPopupFormData > .row > :nth-child(1) > #Name').type('testqa');
     cy.wait(2000);
     cy.get('#loanPopupFormData > .row > :nth-child(2) > #phone').type(9650252279    );
     cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > .float-left').type("noida");
     cy.get('#loanPopupFormData > .row > :nth-child(3) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations').click();
     cy.get('#loanPopupFormData > .fillBtn').click();
     cy.xpath("//div[@class='toast-body']").should('exist');
    });

     it("Loan Offers widget", () => {
     cy.visit("https://trucks.tractorjunction.com/en/maruti-suzuki-truck/super-carry");
     cy.wait(12000);
     cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
  //  cy.get('.modal-content > .close > .filter-img').click();
     cy.get('.mb-3 > .location-position > .new-popup-location > .float-left').type('noida');
     cy.get('.mb-3 > .location-position > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span > .d-block').click();
     cy.get(':nth-child(2) > .form-group > #Name').clear();
     cy.get(':nth-child(2) > .form-group > #Name').type('testqa');
     cy.wait(2000);
     cy.get(':nth-child(3) > .form-group > #phone').type(9650252279    );
     cy.get(':nth-child(4) > .row > .col-12 > .fillBtn').click();
     cy.xpath("//div[@class='toast-body']").should('exist');
    });
    it("Talk to Dealer", () => {
    cy.visit("https://trucks.tractorjunction.com/en/scania-truck/p-320-4x2");
    cy.wait(12000);
    cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
    cy.get('.emiOffer.d-block > .emiOffer-container > .emiOffer-Wrapper > .emiOffer-content > .emiOffer-content-in > .emiOffer-plan-in > .emiOffer-btn > .btn-global').click();
    cy.wait(3000);
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').clear();
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(1) > #name').type("testqa");
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > :nth-child(2) > #mobile').type(9650252279    );
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("noida");
    cy.get('.modal.show > .modal-dialog > .modal-content > .customModal-body > #DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
   // cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Truck Dealers & Service Centers section", () => {
   cy.visit("https://trucks.tractorjunction.com/en/osm-truck/m1ka-10");
   cy.wait(12000);
   cy.get('#splashpopup > .modal-dialog > .modal-content > .close').click();
   cy.get('.dealerBlock-contact > .linkclr').click();
   cy.wait(3000);
    cy.get('#DealerLeadForm > .row > :nth-child(1) > #name').clear();
    cy.get('#DealerLeadForm > .row > :nth-child(1) > #name').type("testqa");
    cy.get('#DealerLeadForm > .row > :nth-child(2) > #mobile').type(9650252279    );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations').click();
    cy.wait(2000);
   // cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(1)').click();
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Find Dealers_Result_Talk to dealer", () => {
    cy.visit("https://trucks.tractorjunction.com/en/dealers/mahindra/uttar-pradesh/noida");
   // cy.wait(12000);
    //cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .dealerBlock-inner > .dealer-inner-content > .dealerBlock-contact > .linkclr').click();
    cy.wait(3000);
    cy.get('#name').clear();
    cy.get('#name').type("testqa");
    cy.get('#mobile').type(9650252279    );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#model_id').select(2);
    //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Find Service Centres_Result_Talk to dealer", () => {
    cy.visit("https://trucks.tractorjunction.com/en/dealers/tata/uttar-pradesh/noida");
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get(':nth-child(1) > .dealerBlock-inner > .dealer-inner-content > .dealerBlock-contact > .linkclr').click();
    cy.wait(3000);
    cy.get('#name').clear();
    cy.get('#name').type("testqa");
    cy.get('#mobile').type(9650252279    );
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
    cy.wait(2000);
    cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.wait(2000);
    cy.get('#model_id').select(2);
    //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
    cy.get('#SubmitDealerLead').click();
    cy.wait(2000);
    cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Spare Parts_Talk to dealer", () => {
   cy.visit("https://trucks.tractorjunction.com/en/spare-parts/ashok-leyland/uttar-pradesh/noida");
 //  cy.wait(12000);
    //cy.get('.modal-content > .close > .filter-img').click();
   cy.get(':nth-child(1) > .newsBlock-dealers > .dealersBlock-content > .talkCard-btn > .btn-global').click();
   cy.wait(3000);
   cy.get('#name').clear();
   cy.get('#name').type("testqa");
   cy.get('#mobile').type(9650252279    );
   cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
   cy.wait(2000);
   cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
   cy.wait(2000);
   cy.get('#brand_id').select(2);
   cy.wait(2000);
   cy.get('#model_id').select(2);
   //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
   cy.get('#SubmitDealerLead').click();
   cy.wait(2000);
   cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Body makers_Talk to dealer", () => {
   cy.visit("https://trucks.tractorjunction.com/en/body-makers/rajasthan/alwar");
  // cy.wait(12000);
  //  cy.get('.modal-content > .close > .filter-img').click();
   cy.get('.talkCard-btn > .btn-global').click();
   cy.wait(3000);
   cy.get('#name').clear();
   cy.get('#name').type("testqa");
   cy.get('#mobile').type(9650252279    );
   cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
   cy.wait(2000);
   cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
   cy.wait(2000);
   cy.get('#brand_id').select(1);
   cy.wait(2000);
   cy.get('#model_id').select(2);
   //cy.get('#DealerLeadForm > .row > .check-group > .check-box-wrp > :nth-child(2)').click();
   cy.get('#SubmitDealerLead').click();
   cy.wait(2000);
   cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Popular Second Hand Truck section", () => {
   cy.visit("https://trucks.tractorjunction.com/en/volvo-truck/fm-420-4x2-lng"); 
   cy.wait(12000);
   cy.get('#splashpopup > .modal-dialog > .modal-content > .close > img').click();
   cy.get(':nth-child(1) > .truckCardSingle-box > .truckCardSingle-cont > .truckCardSingle-btn > .ContactToSeller').click();
   cy.wait(2000);
   cy.get('#contactSellerDetailForm > .row > :nth-child(1) > #name').clear();
   cy.get('#contactSellerDetailForm > .row > :nth-child(1) > #name').type('testqa');
   cy.wait(2000);
   cy.get('#contactSellerDetailForm > .row > :nth-child(2) > #mobile').type(9158593785    );
   cy.wait(2000);
   cy.get('#contactSellerDetailForm > .row > :nth-child(3) > .form-control').type(200);
   cy.get(':nth-child(4) > .new-popup-location > .float-left').type('noida');
   cy.get(':nth-child(4) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
   cy.wait(2000);
   cy.get('#submitContactSeller').click();
   cy.get('#sellerdetailsubmission > .modal-dialog > .modal-content > .customModal-header > .modalHeading').should('exist');
    });

    it("AMP page(product detail)", () => {
    cy.visit("https://trucks.tractorjunction.com/en/tata-truck/signa-4225t-cab6200?amp=1");
    
    cy.wait(2000);
    cy.scrollTo(0,1500);
    cy.wait(2000);
    cy.get(':nth-child(1) > .form-submit-btn').click();
   // cy.wait(12000);
   // cy.get('.modal-content > .close > .filter-img').click();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
    cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type('testqa');
    cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9158593785    );
    cy.get(':nth-child(5) > .new-popup-location > .float-left').type("Noida");
    cy.get(':nth-child(5) > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
    cy.get('#SubmitOnroadPriceForm').click();
    cy.get('.thankscustomModal-header > .modalHeading').should('exist');
    });

    it("Talk to dealer", () => {
     cy.visit("https://trucks.tractorjunction.com/en/body-makers");
     cy.get(':nth-child(11) > .dealerBlock-inner > .dealer-inner-content > .dealerBlock-contact > .linkclr').click();
     cy.get('#name').clear();
     cy.wait(2000);
     cy.get('#name').type('testqa');
     cy.get('#mobile').clear();
     cy.get('#mobile').type('9158593785');
     cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > .float-left').type("Noida");
     cy.wait(2000);
     cy.get('#DealerLeadForm > .row > .col-sm-12 > .new-popup-location > #search-main-location > .loc-module-inner > .serch-location-city > #locations > li > span').click();
     cy.wait(2000);
     cy.get('#SubmitDealerLead').click();

    });










    /*
    it("Altigreen banner", () => {
   cy.visit("https://trucks.tractorjunction.com/");  
   cy.wait(12000);
    cy.get('.modal-content > .close > .filter-img').click();
   cy.wait(3000);
   cy.get('.carousel-control-next-icon').click();
   cy.get('.GetOnRoadPriceForm > .img-fluid').click();
   cy.wait(3000);
   cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
   cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
   cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9650252279    );
   cy.xpath("(//div[@class='loc-edit'])[1]").click();
   cy.get('#onRoadPriceFormData > .row > .col-sm-12.form-group > .form-group-inner > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("Noida");
   cy.get('.hashpop-result > #locations > li > a').click();
  // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
   cy.get('#SubmitOnroadPriceForm').click();
   //cy.xpath("//div[@class='toast-body']").should('exist');
});
    it("Electric Vehicle listing_Altigreen_GORP", () => {
   cy.visit("https://trucks.tractorjunction.com/en/electric"); 
   cy.wait(12000);
    cy.get('.modal-content > .close > .filter-img').click();
   cy.get('.container-mid > .img-fluid').click();
   cy.wait(3000);
   cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').clear();
   cy.get('#onRoadPriceFormData > .row > :nth-child(1) > #Name').type("testqa");
   cy.get('#onRoadPriceFormData > .row > :nth-child(2) > #phone').type(9773375072);
   cy.xpath("(//div[@class='loc-edit'])[2]").click();
   cy.get('#onRoadPriceFormData > .row > .col-sm-12.form-group > .form-group-inner > .hashpop > .forms > .input-box > .input-box-inner > #cityName').type("Noida");
   cy.get('.hashpop-result > #locations > li > a').click();
  // cy.get('#tentative_purchase > .check-box-wrp > :nth-child(1)').click();
   cy.get('#SubmitOnroadPriceForm').click();
   //cy.xpath("//div[@class='toast-body']").should('exist');
});*/
});